tags_index:
    path:     /
    defaults: { _controller: "ServiceBundle:Tags:index" }
    methods:  GET

tags_show:
    path:     /{id}/show
    defaults: { _controller: "ServiceBundle:Tags:show" }
    methods:  GET

tags_new:
    path:     /new
    defaults: { _controller: "ServiceBundle:Tags:new" }
    methods:  [GET, POST]

tags_edit:
    path:     /{id}/edit
    defaults: { _controller: "ServiceBundle:Tags:edit" }
    methods:  [GET, POST]

tags_delete:
    path:     /{id}/delete
    defaults: { _controller: "ServiceBundle:Tags:delete" }
    methods:  DELETE
