users_index:
    path:     /
    defaults: { _controller: "ServiceBundle:Users:index" }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "ServiceBundle:Users:show" }
    methods:  GET
users_auth:
    path:     /auth
    defaults: { _controller: "ServiceBundle:Users:auth" }
    methods:  [GET, POST]

users_new:
    path:     /new
    defaults: { _controller: "ServiceBundle:Users:new" }
    methods:  [GET, POST]

users_profile:
    path:     /profile
    defaults: { _controller: "ServiceBundle:Users:profile" }
    methods:  [GET, POST]

users_profile_edit:
    path:     /profileedit/{id}
    defaults: { _controller: "ServiceBundle:Users:profileedit" }
    methods:  [GET, POST]
users_confirme:
    path:     /confirme
    defaults: { _controller: "ServiceBundle:Users:confirme" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "ServiceBundle:Users:delete" }
    methods:  DELETE
