service_likes:
    resource: "@ServiceBundle/Controller/LikesController.php"
    type:     annotation

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /s

app:
    resource: '@AppBundle/Controller/'
    type: annotation
