<?php

namespace ServiceBundle\Repository;

/**
 * FlowersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowersRepository extends \Doctrine\ORM\EntityRepository
{
}
