app_users:
    resource: "@ServiceBundle/Resources/config/routing/users.yml"
    prefix:   /users
app_post:
    resource: "@ServiceBundle/Resources/config/routing/post.yml"
    prefix:   /posts
app_photo:
    resource: "@ServiceBundle/Resources/config/routing/photo.yml"
    prefix:   /photos
app_tags:
    resource: "@ServiceBundle/Resources/config/routing/tags.yml"
    prefix:   /tags
app_favoris:
    resource: "@ServiceBundle/Resources/config/routing/favoris.yml"
    prefix:   /favoris
app_comments:
    resource: "@ServiceBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
